# Generated by Django 5.2.1 on 2025-06-12 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0019_studentreg_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_houre', models.CharField(choices=[('p', 'Present'), ('A', 'Absent'), ('PE', 'Pending')], default='PE', max_length=2)),
                ('second_houre', models.CharField(choices=[('p', 'Present'), ('A', 'Absent'), ('PE', 'Pending')], default='PE', max_length=2)),
                ('third_houre', models.CharField(choices=[('p', 'Present'), ('A', 'Absent'), ('PE', 'Pending')], default='PE', max_length=2)),
                ('forth_houre', models.CharField(choices=[('p', 'Present'), ('A', 'Absent'), ('PE', 'Pending')], default='PE', max_length=2)),
                ('fifth_houre', models.CharField(choices=[('p', 'Present'), ('A', 'Absent'), ('PE', 'Pending')], default='PE', max_length=2)),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.studentreg')),
            ],
        ),
    ]
