# Generated by Django 5.2.1 on 2025-06-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_studentreg_course'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='fifth_hour',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('PE', 'Pending')], default='PE', max_length=2),
        ),
        migrations.AddField(
            model_name='attendance',
            name='first_hour',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('PE', 'Pending')], default='PE', max_length=2),
        ),
        migrations.AddField(
            model_name='attendance',
            name='fourth_hour',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('PE', 'Pending')], default='PE', max_length=2),
        ),
        migrations.AddField(
            model_name='attendance',
            name='second_hour',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('PE', 'Pending')], default='PE', max_length=2),
        ),
        migrations.AddField(
            model_name='attendance',
            name='third_hour',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('PE', 'Pending')], default='PE', max_length=2),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='fifth_houre',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='first_houre',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='forth_houre',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='second_houre',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='third_houre',
        ),
    ]
