# Generated by Django 5.2.1 on 2025-06-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='today',
            field=models.IntegerField(default=0),
        ),
    ]
