# Generated by Django 5.2.1 on 2025-06-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_attendance_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='today',
            field=models.FloatField(default=0),
        ),
    ]
