# Generated by Django 5.2.1 on 2025-06-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_attendance_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='sem',
            field=models.IntegerField(default=0),
        ),
    ]
