# Generated by Django 5.2.1 on 2025-06-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_attendance_sem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
