# Generated by Django 5.2.1 on 2025-06-08 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0003_delete_positions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
