# Generated by Django 5.2.1 on 2026-07-22 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0050_examregistration_marklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], default='P', max_length=2)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('office_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='index.officefacultyregistration')),
            ],
            options={
                'unique_together': {('office_staff', 'date')},
            },
        ),
    ]
