# Generated by Django 5.2.1 on 2026-07-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeattendance',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
