# Generated by Django 5.2.1 on 2026-08-17 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0051_logintable_registered_on'),
        ('office', '0002_officeattendance_checked_out_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('leave_type', models.CharField(choices=[('ML', 'Medical Leave'), ('CL', 'Casual Leave'), ('DL', 'Duty Leave'), ('VL', 'Vacation Leave'), ('OL', 'Other Leave')], default='CL', max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('submitted_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=2)),
                ('num_of_days', models.FloatField()),
                ('office_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='index.officefacultyregistration')),
            ],
        ),
    ]
