# Generated by Django 5.2.1 on 2026-08-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_officeleaveapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeleaveapplication',
            name='day_type',
            field=models.CharField(choices=[('full', 'Full Day'), ('half', 'Half Day')], default='full', max_length=10),
        ),
        migrations.AlterField(
            model_name='officeleaveapplication',
            name='num_of_days',
            field=models.FloatField(default=1.0),
        ),
    ]
