# Generated by Django 5.2.1 on 2026-08-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_officeleaveapplication_day_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeattendance',
            name='marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
