# Generated by Django 5.2.1 on 2025-05-27 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.CharField(max_length=20)),
                ('head', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('V', 'varified'), ('P', 'Penting'), ('R', 'Rejected')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StaffReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('staff_id', models.CharField(max_length=20)),
                ('dep', models.CharField(max_length=20)),
                ('pho', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=20)),
                ('login_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='StudentReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('reg_no', models.IntegerField()),
                ('pho', models.CharField(max_length=15)),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.deptable')),
                ('login_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.logintable')),
            ],
        ),
    ]
