# Generated by Django 5.2.1 on 2025-05-27 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_staffreg_dep'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('pho', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default=None, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='studentreg',
            name='parent_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_1', to='index.parentreg'),
        ),
        migrations.AddField(
            model_name='studentreg',
            name='parent_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_2', to='index.parentreg'),
        ),
    ]
