# Generated by Django 5.2.1 on 2025-05-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_parentreg_studentreg_parent_1_studentreg_parent_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptable',
            name='dep',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
