# Generated by Django 5.2.1 on 2025-05-27 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_deptable_dep'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.positiontable'),
        ),
    ]
