# Generated by Django 5.2.1 on 2025-05-27 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_positiontable_alter_staffreg_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentreg',
            name='login_info',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='index.logintable'),
            preserve_default=False,
        ),
    ]
