# Generated by Django 5.2.1 on 2025-05-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_parentreg_login_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreg',
            name='parent_2',
        ),
    ]
