# Generated by Django 5.2.1 on 2025-05-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_guadinreg_alter_studentreg_parent_1_delete_parentreg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guadinreg',
            old_name='name',
            new_name='Guadin_Name',
        ),
        migrations.RenameField(
            model_name='guadinreg',
            old_name='pho',
            new_name='Guadin_phone_Number',
        ),
        migrations.RemoveField(
            model_name='guadinreg',
            name='gender',
        ),
        migrations.AddField(
            model_name='guadinreg',
            name='Guadin_email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
