# Generated by Django 5.2.1 on 2025-05-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_rename_name_guadinreg_guadin_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='user',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
