# Generated by Django 5.2.1 on 2025-05-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_logintable_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreg',
            name='staff_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
