# Generated by Django 5.2.1 on 2025-05-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_alter_staffreg_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='status',
            field=models.CharField(choices=[('V', 'Verified'), ('P', 'Pending'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
