# Generated by Django 5.2.1 on 2025-05-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_logintable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreg',
            name='sem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
