# Generated by Django 5.2.1 on 2025-05-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_studentreg_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreg',
            name='year_of_admision',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
