# Generated by Django 5.2.1 on 2025-05-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_studentreg_year_of_admision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deptable',
            name='head',
        ),
    ]
