# Generated by Django 5.2.1 on 2025-05-31 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_remove_deptable_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffreg',
            name='position',
        ),
        migrations.DeleteModel(
            name='PositionTable',
        ),
    ]
