# Generated by Django 5.2.1 on 2025-06-08 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_positions_staffreg_pos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=20)),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.deptable')),
            ],
        ),
    ]
