# Generated by Django 5.2.1 on 2025-06-08 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreg',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.course'),
        ),
    ]
