# Generated by Django 5.2.1 on 2025-06-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_studentreg_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='status',
            field=models.CharField(choices=[('V', 'Verified'), ('P', 'Pending'), ('R', 'Rejected'), ('PA', 'PassOut'), ('DO', 'DroupOut'), ('TR', 'Transfer'), ('RE', 'Resign')], default='P', max_length=2),
        ),
    ]
