# Generated by Django 5.2.1 on 2025-06-19 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_alter_logintable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_hour', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('PE', 'Pending')], default='PE', max_length=2)),
                ('second_hour', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('PE', 'Pending')], default='PE', max_length=2)),
                ('third_hour', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('PE', 'Pending')], default='PE', max_length=2)),
                ('fourth_hour', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('PE', 'Pending')], default='PE', max_length=2)),
                ('fifth_hour', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('PE', 'Pending')], default='PE', max_length=2)),
                ('today', models.FloatField(default=0)),
                ('sem', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.studentreg')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
