# Generated by Django 5.2.1 on 2025-06-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_alter_logintable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deptable',
            name='dep',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='guadinreg',
            name='Guadin_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='positions',
            name='pos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='staff_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
