# Generated by Django 5.2.1 on 2025-06-22 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_alter_course_course_alter_deptable_dep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('leave_type', models.CharField(choices=[('ML', 'Medical Leave'), ('CL', 'Casual Leave'), ('EL', 'Earned Leave'), ('LOP', 'Loss of Pay')], max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('submitted_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('from_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications_sent', to='index.staffreg')),
                ('to_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_applications_received', to='index.staffreg')),
            ],
        ),
    ]
