# Generated by Django 5.2.1 on 2025-06-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_leaveapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='subject',
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('H', 'HOD Approved'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
