# Generated by Django 5.2.1 on 2025-06-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_alter_leaveapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('H', 'HOD Approved'), ('HR', 'HOD Rejected'), ('FH', 'From HOD'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=2),
        ),
    ]
