# Generated by Django 5.2.1 on 2025-06-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_alter_leaveapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='num_of_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('ML', 'Medical Leave'), ('CL', 'Casual Leave')], max_length=3),
        ),
    ]
