# Generated by Django 5.2.1 on 2025-06-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_leaveapplication_num_of_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='num_of_days',
            field=models.FloatField(),
        ),
    ]
