# Generated by Django 5.2.1 on 2025-06-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_alter_leaveapplication_num_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('ML', 'Medical Leave'), ('CL', 'Casual Leave'), ('DL', 'Duty Leave'), ('VL', 'Vacation Leave')], max_length=3),
        ),
    ]
