# Generated by Django 5.2.1 on 2025-06-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0030_alter_leaveapplication_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
