# Generated by Django 5.2.1 on 2025-06-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0031_logintable_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='fifth_hour',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('NA', 'Pending')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='first_hour',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('NA', 'Pending')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='fourth_hour',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('NA', 'Pending')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='second_hour',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('NA', 'Pending')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='third_hour',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('NA', 'Pending')], default='PE', max_length=2),
        ),
    ]
