# Generated by Django 5.2.1 on 2025-06-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0034_alter_attendance_fifth_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffreg',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='studentreg',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentreg',
            name='blod_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
