# Generated by Django 5.2.1 on 2025-06-26 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0035_remove_staffreg_staff_id_studentreg_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentreg',
            old_name='blod_type',
            new_name='blood_type',
        ),
    ]
