# Generated by Django 5.2.1 on 2025-06-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0036_rename_blod_type_studentreg_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffreg',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_profiles/'),
        ),
    ]
