# Generated by Django 5.2.1 on 2025-08-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0037_staffreg_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='fifth_attendance_taken_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='fifth_attendance_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='first_attendance_taken_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='first_attendance_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='fourth_attendance_taken_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='fourth_attendance_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='second_attendance_taken_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='second_attendance_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='third_attendance_taken_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='third_attendance_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
