# Generated by Django 5.2.1 on 2025-08-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0038_attendance_fifth_attendance_taken_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guadinreg',
            name='Guadin_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
