# Generated by Django 5.2.1 on 2025-08-17 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0039_alter_guadinreg_guadin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreg',
            name='dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.deptable'),
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='pos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.positions'),
        ),
    ]
