# Generated by Django 5.2.1 on 2025-08-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0040_alter_staffreg_dep_alter_staffreg_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreg',
            name='dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.deptable'),
        ),
    ]
