# Generated by Django 5.2.1 on 2025-08-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0041_alter_studentreg_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreg',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
