# Generated by Django 5.2.1 on 2025-08-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0042_alter_studentreg_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreg',
            name='blood_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
