# Generated by Django 5.2.1 on 2025-08-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0043_alter_studentreg_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
