# Generated by Django 5.2.1 on 2025-08-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0044_alter_course_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('H', 'HOD Approved'), ('HR', 'HOD Rejected'), ('FH', 'From HOD'), ('A', 'principal Approved'), ('R', 'principal Rejected')], default='P', max_length=2),
        ),
    ]
