# Generated by Django 5.2.1 on 2025-08-18 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0045_alter_leaveapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreg',
            name='dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.deptable'),
        ),
    ]
