# Generated by Django 5.2.1 on 2025-08-18 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0046_alter_staffreg_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.deptable'),
        ),
    ]
