# Generated by Django 5.2.1 on 2026-07-20 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0047_alter_course_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='auto_login_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentreg',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='index.course'),
        ),
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField(blank=True, null=True)),
                ('exam_type', models.CharField(choices=[('CT', 'Class Test'), ('ME', 'Model Exam'), ('SE', 'Sem Exam')], max_length=2)),
                ('exam_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=50)),
                ('total_mark', models.IntegerField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.course')),
            ],
        ),
        migrations.CreateModel(
            name='MarkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.examregistration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.studentreg')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeFacultyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('OH', 'Office Head'), ('BS', 'Billing Staff'), ('OS', 'Other Staff')], max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('login_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_hour_subject', models.CharField(max_length=50)),
                ('first_houre_staff', models.CharField(max_length=50)),
                ('second_hour_subject', models.CharField(max_length=50)),
                ('second_hour_staff', models.CharField(max_length=50)),
                ('third_hour_subject', models.CharField(max_length=50)),
                ('third_hour_staff', models.CharField(max_length=50)),
                ('fourth_hour_subject', models.CharField(max_length=50)),
                ('fourth_hour_staff', models.CharField(max_length=50)),
                ('fifth_hour_subject', models.CharField(max_length=50)),
                ('fifth_hour_staff', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sem', models.IntegerField(blank=True, null=True)),
                ('day', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='M', max_length=2)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.course')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='todays_time_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.timetable'),
        ),
    ]
