# Generated by Django 5.2.1 on 2025-12-29 08:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0048_logintable_auto_login_id_alter_studentreg_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='auto_login_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
