# Generated by Django 5.2.1 on 2026-07-22 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0050_examregistration_marklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='registered_on',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
