# Generated by Django 5.2.1 on 2026-08-30 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0052_feestructure_studentfee_feepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='course',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='sem',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', max_length=2),
        ),
        migrations.CreateModel(
            name='TimeTableSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.course')),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='timetable_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='index.timetableset'),
        ),
    ]
