# Generated by Django 5.2.1 on 2026-08-30 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0053_remove_timetable_course_remove_timetable_sem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='timetable_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='index.timetableset'),
        ),
    ]
