# Generated by Django 5.2.1 on 2026-08-30 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0054_alter_timetable_timetable_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='timetable_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='index.timetableset'),
        ),
    ]
