# Generated by Django 5.2.1 on 2026-09-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0055_alter_timetable_timetable_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreg',
            name='seat_type',
            field=models.CharField(blank=True, choices=[('MG', 'Management Seat'), ('MS', 'Merit Seat')], max_length=2, null=True),
        ),
    ]
