# Generated by Django 5.2.1 on 2026-09-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0056_studentreg_seat_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='amount',
            new_name='merit_amount',
        ),
    ]
