# Generated by Django 5.2.1 on 2026-09-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0057_rename_amount_feestructure_merit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='management_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
