# Generated by Django 5.2.1 on 2026-09-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0058_feestructure_management_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpiPaymentSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('qr_code', models.ImageField(blank=True, max_length=255, null=True, upload_to='upi_qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'upi_payment_settings',
            },
        ),
    ]
