# Generated by Django 5.2.1 on 2026-09-21 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0059_upipaymentsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50, unique=True)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.deptable')),
            ],
        ),
        migrations.AddField(
            model_name='studentreg',
            name='minor_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='index.minorcourse'),
        ),
    ]
