# Generated by Django 5.2.1 on 2026-09-29 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0060_minorcourse_studentreg_minor_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreg',
            name='minor_course',
        ),
        migrations.CreateModel(
            name='StudentMinorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='index.minorcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minor_courses', to='index.studentreg')),
            ],
        ),
    ]
